import type { Vendor, ServiceHistory } from './types';
export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'v1',
    name: 'Precision Auto Works',
    address: '123 Mechanic Lane, Savannah, GA',
    description: 'Specializing in European models, Precision Auto Works offers top-tier diagnostics and mechanical repairs with factory-grade equipment. Our lead technician is a SCAD alumnus with a passion for performance tuning.',
    scadRate: 95,
    isAlumniOwned: true,
    isParentOwned: false,
    yearsInNetwork: 7,
    services: ['Mechanical', 'Diagnostics'],
    reviews: [
      { author: 'Jane D.', rating: 5, comment: 'Fast and reliable service! They fixed my BMW when no one else could.' },
      { author: 'John S.', rating: 4, comment: 'Good work, a bit pricey but you get what you pay for.' },
    ],
  },
  {
    id: 'v2',
    name: 'Savannah Bumper & Glass',
    address: '456 Body Shop Blvd, Savannah, GA',
    description: 'From minor dents to major collision repair, our family-owned shop (proud SCAD parent!) brings cars back to life. We use eco-friendly paints and offer a lifetime guarantee on all our work.',
    scadRate: 88,
    isAlumniOwned: false,
    isParentOwned: true,
    yearsInNetwork: 10,
    services: ['Body/Glass'],
    reviews: [
      { author: 'Emily R.', rating: 5, comment: 'My car looks brand new! The color match is perfect.' },
      { author: 'Chris B.', rating: 5, comment: 'Excellent customer service and flawless glass replacement.' },
    ],
  },
  {
    id: 'v3',
    name: 'Quick Lube Express',
    address: '789 Oil Change Ave, Savannah, GA',
    description: 'The fastest and friendliest quick service in town. We handle all routine maintenance, from oil changes to tire rotations, using only premium synthetic oils and top-quality parts. No appointment necessary.',
    scadRate: 92,
    isAlumniOwned: false,
    isParentOwned: false,
    yearsInNetwork: 5,
    services: ['Quick Service'],
    reviews: [
      { author: 'Mike T.', rating: 5, comment: 'In and out in 20 minutes, just as promised. Great value.' },
    ],
  },
  {
    id: 'v4',
    name: 'Total Car Care',
    address: '101 Repair Row, Savannah, GA',
    description: 'Your one-stop shop for everything your car needs. Co-owned by a SCAD alumnus and a SCAD parent, we combine technical expertise with a commitment to our community. We handle everything from oil changes to complex diagnostics.',
    scadRate: 90,
    isAlumniOwned: true,
    isParentOwned: true,
    yearsInNetwork: 6,
    services: ['Mechanical', 'Diagnostics', 'Quick Service'],
    reviews: [
        { author: 'Sarah K.', rating: 5, comment: 'They diagnosed a tricky issue other shops missed. Honest and transparent.' },
        { author: 'David L.', rating: 4, comment: 'Solid work, fair pricing. My go-to for all car issues.' },
    ],
  },
];
export const MOCK_SERVICE_HISTORY: ServiceHistory[] = [
    {
        id: 'h1',
        vendorName: 'Precision Auto Works',
        service: 'Brake Pad Replacement',
        date: new Date('2023-10-15'),
        cost: 450.00,
        warrantyExpires: new Date('2024-10-15'),
    },
    {
        id: 'h2',
        vendorName: 'Quick Lube Express',
        service: 'Full Synthetic Oil Change',
        date: new Date('2023-08-01'),
        cost: 89.99,
        warrantyExpires: null,
    },
    {
        id: 'h3',
        vendorName: 'Savannah Bumper & Glass',
        service: 'Windshield Chip Repair',
        date: new Date('2023-05-20'),
        cost: 120.00,
        warrantyExpires: new Date('2024-05-20'),
    },
    {
        id: 'h4',
        vendorName: 'Total Car Care',
        service: 'Check Engine Light Diagnostics',
        date: new Date('2023-03-10'),
        cost: 75.00,
        warrantyExpires: null,
    }
];